### ISSUE TITLE
cd not working properly with tab functionality

### ISSUE THREAD

**Issue by younesbram** [dthree/cash#127] opened 2022-10-20 13:23 UTC
installed cash with npm,
typed cash in windows, ls works looks good everything.
when i type in ` cd New ` and hit tab, it goes to `cd New Folder/` , however this creates a bug:
`no such file or directory chdir C:\whatever -> 'New'`
obviously easy fix just to add an apostrophe ( ' ) to make it a string but, please fix this can just make it always take in the whole thing and stringify input when its cd.

**Comment by nfischer** [comment] 2022-10-25 06:46
I think this is a duplicate of #32. There are a few known issues around tab completion.

**Closed as completed by nfischer** 2022-10-25 06:46 UTC
Labels: bug, duplicate
