### ISSUE TITLE
[Windows 10] npm install cash-global -g does not work

### ISSUE THREAD

**Issue by taslimy** [dthree/cash#117] opened 2017-10-25 21:28 UTC
1.  `npm install cash-global -g`

Error: 
2. ` 'ls' is not recognized as an internal or external command, operable program or batch file.`

```
C:\Users\Taslim>node -v
v6.11.2

C:\Users\Taslim>npm -v
3.10.10
```

Am i doing something incorrect?

**Comment by nfischer** [comment] 2017-10-26 01:39
Duplicate of #83

**Comment by nfischer** [comment] 2017-10-26 01:40
Unfortunately, I don't think we ever solved this issue. I'm not very knowledgeable in this area.

**Closed as completed by nfischer** 2017-10-26 01:39 UTC
Labels: duplicate

**Comment by taslimy** [comment] 2017-10-26 02:02
Hi this isn't fix but if you you Windows PowerShell LS works but `TOUCH` doesn't in replacement for touch I use `new-item` it's the same way to create a file. Just my own work around after my own research until i await a fix. 

Little Example Below hope it helps fellow users. 
```
PS C:\Users\Taslim\desktop> mkdir test


    Directory: C:\Users\Taslim\desktop


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       10/25/2017  10:01 PM                test


PS C:\Users\Taslim\desktop> cd test
PS C:\Users\Taslim\desktop\test> new-item test.js


    Directory: C:\Users\Taslim\desktop\test


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       10/25/2017  10:01 PM              0 test.js


PS C:\Users\Taslim\desktop\test> ls


    Directory: C:\Users\Taslim\desktop\test


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       10/25/2017  10:01 PM              0 test.js
```

**Comment by taslimy** [comment] 2017-10-26 02:44
Alternatively i did this just to got all the commands through Unxutils which is just a port which works on windows.
 https://www.julienklepatch.com/improve-windows-command-line/#section2

<h4>Steps to install</h4>
<p>1. Download Unxutils and unzip it to your `C:\`  </p>
<p>2. Rename the folder to `unxutils` to have it all in lowercase letters. </p>
<p>3. Navigate it to add environment variables. search `edit system environment variables` on win 10.</p>
<p>4. A window called System Properties will show up and if you not in the `Advanced Tab` click that tab and at the bottom you'll see Environment Variables</p>
<p> 5. Then click `new` and window will pop up asking you to input the variables. </p>
<p>

<p>Variable name: PATH</p>
<p>Variable Value: C:\unxutils\usr\local\wbin</p>

</p>
<p>6. Then click ok.</p>
<p>7. Use Windows PowerShell everything will works as it should.</p>

<h4>My Demo using Windows PowerShell</h4>

```
PS C:\Users\Taslim> cd desktop
PS C:\Users\Taslim\desktop> mkdir test2


    Directory: C:\Users\Taslim\desktop


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       10/25/2017  10:46 PM                test2


PS C:\Users\Taslim\desktop> cd test2
PS C:\Users\Taslim\desktop\test2> touch index.html index.js index.css
PS C:\Users\Taslim\desktop\test2> ls


    Directory: C:\Users\Taslim\desktop\test2


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       10/25/2017  10:47 PM              0 index.css
-a----       10/25/2017  10:47 PM              0 index.html
-a----       10/25/2017  10:47 PM              0 index.js

```

<p>Hope this helps anyone.</p>
